/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpackage;

import java.awt.*;
import java.awt.event.MouseEvent;
import javax.swing.*;
import static javax.swing.BorderFactory.*;

/**
 *
 * @author Ivan Flavano
 */
public class BudgetAppX extends javax.swing.JFrame {
    private String selectedTab = "";
    private int x,y;
    
    /**
     * Creates new form BudgetAppX
     */
    public BudgetAppX() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Background = new javax.swing.JPanel();
        pnl_TitleBar = new javax.swing.JPanel();
        lb_Exit = new javax.swing.JLabel();
        lb_Minimize = new javax.swing.JLabel();
        pnl_Title = new javax.swing.JPanel();
        pnl_NavBar = new javax.swing.JPanel();
        pnl_MainDashB = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnl_Transactions = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnl_BudSum = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnl_Settings = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnl_About = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnl_Container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);

        pnl_Background.setBackground(new java.awt.Color(0, 0, 0));

        pnl_TitleBar.setBackground(new java.awt.Color(0, 0, 0));
        pnl_TitleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_TitleBarMouseDragged(evt);
            }
        });
        pnl_TitleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_TitleBarMousePressed(evt);
            }
        });

        lb_Exit.setBackground(new java.awt.Color(255, 255, 255));
        lb_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/res/icons/round_clear_white_14.png"))); // NOI18N
        lb_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_ExitMouseClicked(evt);
            }
        });

        lb_Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/res/icons/round_remove_white_14.png"))); // NOI18N
        lb_Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_MinimizeMouseClicked(evt);
            }
        });

        pnl_Title.setBackground(new java.awt.Color(32, 32, 32));

        javax.swing.GroupLayout pnl_TitleLayout = new javax.swing.GroupLayout(pnl_Title);
        pnl_Title.setLayout(pnl_TitleLayout);
        pnl_TitleLayout.setHorizontalGroup(
            pnl_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );
        pnl_TitleLayout.setVerticalGroup(
            pnl_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl_TitleBarLayout = new javax.swing.GroupLayout(pnl_TitleBar);
        pnl_TitleBar.setLayout(pnl_TitleBarLayout);
        pnl_TitleBarLayout.setHorizontalGroup(
            pnl_TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_TitleBarLayout.createSequentialGroup()
                .addComponent(pnl_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_Minimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_Exit)
                .addContainerGap())
        );
        pnl_TitleBarLayout.setVerticalGroup(
            pnl_TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_Minimize)
                    .addComponent(lb_Exit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnl_Title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_NavBar.setBackground(new java.awt.Color(32, 32, 32));

        pnl_MainDashB.setBackground(new java.awt.Color(32, 32, 32));
        pnl_MainDashB.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(252, 215, 54)));
        pnl_MainDashB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_MainDashBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_MainDashBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_MainDashBMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/res/icons/dashboard.png"))); // NOI18N
        jLabel7.setText("      Main Dashboard");
        jLabel7.setToolTipText("");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_MainDashBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_MainDashBLayout = new javax.swing.GroupLayout(pnl_MainDashB);
        pnl_MainDashB.setLayout(pnl_MainDashBLayout);
        pnl_MainDashBLayout.setHorizontalGroup(
            pnl_MainDashBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_MainDashBLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        pnl_MainDashBLayout.setVerticalGroup(
            pnl_MainDashBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_MainDashBLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnl_Transactions.setBackground(new java.awt.Color(32, 32, 32));
        pnl_Transactions.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        pnl_Transactions.setForeground(new java.awt.Color(32, 32, 32));
        pnl_Transactions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_TransactionsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_MainDashBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_MainDashBMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/res/icons/history.png"))); // NOI18N
        jLabel5.setText("      Transactions");
        jLabel5.setToolTipText("");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_TransactionsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_TransactionsLayout = new javax.swing.GroupLayout(pnl_Transactions);
        pnl_Transactions.setLayout(pnl_TransactionsLayout);
        pnl_TransactionsLayout.setHorizontalGroup(
            pnl_TransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TransactionsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_TransactionsLayout.setVerticalGroup(
            pnl_TransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TransactionsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnl_BudSum.setBackground(new java.awt.Color(32, 32, 32));
        pnl_BudSum.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        pnl_BudSum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_BudSumMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_MainDashBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_MainDashBMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/res/icons/list_alt.png"))); // NOI18N
        jLabel6.setText("      Budget Summary");
        jLabel6.setToolTipText("");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_BudSumMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_BudSumLayout = new javax.swing.GroupLayout(pnl_BudSum);
        pnl_BudSum.setLayout(pnl_BudSumLayout);
        pnl_BudSumLayout.setHorizontalGroup(
            pnl_BudSumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_BudSumLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_BudSumLayout.setVerticalGroup(
            pnl_BudSumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_BudSumLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnl_Settings.setBackground(new java.awt.Color(32, 32, 32));
        pnl_Settings.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        pnl_Settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_SettingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_MainDashBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_MainDashBMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/res/icons/settings.png"))); // NOI18N
        jLabel9.setText("      Settings");
        jLabel9.setToolTipText("");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_SettingsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_SettingsLayout = new javax.swing.GroupLayout(pnl_Settings);
        pnl_Settings.setLayout(pnl_SettingsLayout);
        pnl_SettingsLayout.setHorizontalGroup(
            pnl_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SettingsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_SettingsLayout.setVerticalGroup(
            pnl_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SettingsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnl_About.setBackground(new java.awt.Color(32, 32, 32));
        pnl_About.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        pnl_About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_AboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_MainDashBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_MainDashBMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/res/icons/outline_info_white_18dp.png"))); // NOI18N
        jLabel10.setText("      About");
        jLabel10.setToolTipText("");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_AboutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_AboutLayout = new javax.swing.GroupLayout(pnl_About);
        pnl_About.setLayout(pnl_AboutLayout);
        pnl_AboutLayout.setHorizontalGroup(
            pnl_AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_AboutLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_AboutLayout.setVerticalGroup(
            pnl_AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_AboutLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_NavBarLayout = new javax.swing.GroupLayout(pnl_NavBar);
        pnl_NavBar.setLayout(pnl_NavBarLayout);
        pnl_NavBarLayout.setHorizontalGroup(
            pnl_NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Transactions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_BudSum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_MainDashB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_Settings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_About, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_NavBarLayout.setVerticalGroup(
            pnl_NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_NavBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_MainDashB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnl_Transactions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnl_BudSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(pnl_Settings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnl_About, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        pnl_Container.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnl_ContainerLayout = new javax.swing.GroupLayout(pnl_Container);
        pnl_Container.setLayout(pnl_ContainerLayout);
        pnl_ContainerLayout.setHorizontalGroup(
            pnl_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );
        pnl_ContainerLayout.setVerticalGroup(
            pnl_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl_BackgroundLayout = new javax.swing.GroupLayout(pnl_Background);
        pnl_Background.setLayout(pnl_BackgroundLayout);
        pnl_BackgroundLayout.setHorizontalGroup(
            pnl_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_BackgroundLayout.createSequentialGroup()
                .addComponent(pnl_NavBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnl_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnl_TitleBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_BackgroundLayout.setVerticalGroup(
            pnl_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_BackgroundLayout.createSequentialGroup()
                .addComponent(pnl_TitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnl_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_NavBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_BackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(pnl_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    //EXIT BUTTON
    private void lb_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lb_ExitMouseClicked
    
    //MINIMIZE BUTTON
    private void lb_MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_MinimizeMouseClicked
        setState(this.ICONIFIED);
    }//GEN-LAST:event_lb_MinimizeMouseClicked
    
    //MOVE WINDOW PRESS
    private void pnl_TitleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_TitleBarMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_pnl_TitleBarMousePressed

    //MOVE WINDOW DRAG
    private void pnl_TitleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_TitleBarMouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        setLocation(xx-x, yy-y);
        
    }//GEN-LAST:event_pnl_TitleBarMouseDragged
    
    // ----- NAVIGATION BAR - MOUSE ENTERED ------ //
    private void pnl_MainDashBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_MainDashBMouseEntered
        evt.getComponent().setBackground(new Color(66, 66, 66));
    }//GEN-LAST:event_pnl_MainDashBMouseEntered
    
    // ----- NAVIGATION BAR - MOUSE EXIT  ------ //
    
    private void pnl_MainDashBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_MainDashBMouseExited
        java.awt.Point p = new java.awt.Point(evt.getLocationOnScreen());
        SwingUtilities.convertPointFromScreen(p, evt.getComponent());
        if(evt.getComponent().contains(p)){
            return;
        }
        evt.getComponent().setBackground(new Color(32, 32, 32));
    }//GEN-LAST:event_pnl_MainDashBMouseExited

    
    // ----- NAVIGATION BAR - MOUSE CLICK  ------ //
    private void pnl_MainDashBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_MainDashBMouseClicked
        navbtn_OnClick(evt, pnl_MainDashB);
    }//GEN-LAST:event_pnl_MainDashBMouseClicked

    private void pnl_BudSumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_BudSumMouseClicked
        navbtn_OnClick(evt, pnl_BudSum);
    }//GEN-LAST:event_pnl_BudSumMouseClicked

    private void pnl_SettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_SettingsMouseClicked
        navbtn_OnClick(evt, pnl_Settings);
    }//GEN-LAST:event_pnl_SettingsMouseClicked

    private void pnl_AboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_AboutMouseClicked
        navbtn_OnClick(evt, pnl_About);
    }//GEN-LAST:event_pnl_AboutMouseClicked

    // ----- NAVIGATION BAR - MOUSE CLICKED ------ //
    
    private void pnl_TransactionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_TransactionsMouseClicked
        navbtn_OnClick(evt, pnl_Transactions);
    }//GEN-LAST:event_pnl_TransactionsMouseClicked
    
    
    
    // ------------------------------------------ CUSTOM METHODS ------------------------------------------ //
    
    
    // Navigation Bar - Mouse Clicked
    private void navbtn_OnClick(MouseEvent evt, JPanel pnl){
        pnl_MainDashB.setBorder(createEmptyBorder(0, 5, 0, 0));
        pnl_Transactions.setBorder(createEmptyBorder(0, 5, 0, 0));
        pnl_BudSum.setBorder(createEmptyBorder(0, 5, 0, 0));
        pnl_Settings.setBorder(createEmptyBorder(0, 5, 0, 0));
        pnl_About.setBorder(createEmptyBorder(0, 5, 0, 0));
        
        pnl.setBorder(createMatteBorder(0, 5, 0, 0, new Color(252,215,54)));
        
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BudgetAppX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BudgetAppX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BudgetAppX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BudgetAppX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BudgetAppX().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lb_Exit;
    private javax.swing.JLabel lb_Minimize;
    private javax.swing.JPanel pnl_About;
    private javax.swing.JPanel pnl_Background;
    private javax.swing.JPanel pnl_BudSum;
    private javax.swing.JPanel pnl_Container;
    private javax.swing.JPanel pnl_MainDashB;
    private javax.swing.JPanel pnl_NavBar;
    private javax.swing.JPanel pnl_Settings;
    private javax.swing.JPanel pnl_Title;
    private javax.swing.JPanel pnl_TitleBar;
    private javax.swing.JPanel pnl_Transactions;
    // End of variables declaration//GEN-END:variables
}
